# Google Cloud Build configuration for GNB Transfer
# This file defines the build steps for Cloud Build to deploy to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gnb-transfer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gnb-transfer:latest'
      - '.'
    timeout: 1200s

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gnb-transfer:$COMMIT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gnb-transfer:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gnb-transfer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gnb-transfer:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/gnb-transfer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gnb-transfer:latest'

# Build timeout (20 minutes)
timeout: 1200s

# Use a more powerful machine for faster builds
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  # Increase disk size for node_modules
  diskSizeGb: 100

# Substitutions (can be overridden at build time)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'gnb-transfer'
