#!/bin/bash
# Secret Rotation Script for GNB Transfer
# This script provides step-by-step instructions to rotate exposed secrets

set -e

echo "=============================================="
echo "  GNB Transfer - Secret Rotation Guide"
echo "=============================================="
echo ""
echo "⚠️  WARNING: Exposed secrets MUST be rotated immediately!"
echo ""
echo "The following secrets were exposed in git history and need rotation:"
echo "  1. MONGO_URI (MongoDB connection string)"
echo "  2. JWT_SECRET (JWT signing secret)"
echo "  3. OPENAI_API_KEY (if set)"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${RED}═══════════════════════════════════════════${NC}"
echo -e "${RED}  STEP 1: Rotate MongoDB Credentials${NC}"
echo -e "${RED}═══════════════════════════════════════════${NC}"
echo ""
echo "1. Log into MongoDB Atlas: https://cloud.mongodb.com"
echo "2. Navigate to: Database Access → Database Users"
echo "3. Find user: agunbeyi_db_user"
echo "4. Click 'Edit' → 'Edit Password'"
echo "5. Generate a new strong password (min 20 chars, mixed case, numbers, symbols)"
echo "6. Save the new password"
echo ""
echo "7. Update connection string in backend/.env:"
echo "   OLD: mongodb+srv://agunbeyi_db_user:OPeBZOSlSQgs8JAg@cluster0..."
echo "   NEW: mongodb+srv://agunbeyi_db_user:NEW_PASSWORD_HERE@cluster0..."
echo ""
echo "8. Test connection:"
echo "   cd backend && npm start"
echo "   (Verify app connects to MongoDB successfully)"
echo ""
echo -e "${YELLOW}Option B: Create new database user (recommended)${NC}"
echo "   1. Create new user with different name"
echo "   2. Grant same permissions as old user"
echo "   3. Update MONGO_URI in backend/.env"
echo "   4. Test connection"
echo "   5. Delete old user: agunbeyi_db_user"
echo ""
read -p "Press Enter after rotating MongoDB credentials..."

echo ""
echo -e "${RED}═══════════════════════════════════════════${NC}"
echo -e "${RED}  STEP 2: Rotate JWT_SECRET${NC}"
echo -e "${RED}═══════════════════════════════════════════${NC}"
echo ""
echo "Generate a new strong JWT secret:"
echo ""

# Generate new JWT secret
NEW_JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
echo -e "${GREEN}Generated new JWT_SECRET:${NC}"
echo "$NEW_JWT_SECRET"
echo ""
echo "⚠️  Copy this secret and save it securely!"
echo ""
echo "1. Update backend/.env:"
echo "   JWT_SECRET=$NEW_JWT_SECRET"
echo ""
echo "2. Update in production environment:"
echo "   - Vercel: Project Settings → Environment Variables"
echo "   - Railway: Project → Variables"
echo "   - Render: Dashboard → Environment"
echo ""
echo "3. Redeploy application to production"
echo ""
echo -e "${YELLOW}⚠️  WARNING: Changing JWT_SECRET will invalidate all existing tokens!${NC}"
echo "   - All users will be logged out"
echo "   - They will need to log in again"
echo "   - Notify users before rotating in production"
echo ""
read -p "Press Enter after rotating JWT_SECRET..."

echo ""
echo -e "${RED}═══════════════════════════════════════════${NC}"
echo -e "${RED}  STEP 3: Rotate OpenAI API Key (if set)${NC}"
echo -e "${RED}═══════════════════════════════════════════${NC}"
echo ""
echo "If OPENAI_API_KEY was set in the exposed .env:"
echo ""
echo "1. Log into OpenAI Platform: https://platform.openai.com"
echo "2. Navigate to: API Keys"
echo "3. Find the old key and click 'Delete' or 'Revoke'"
echo "4. Create a new API key"
echo "5. Update backend/.env:"
echo "   OPENAI_API_KEY=sk-proj-new-key-here"
echo "6. Update in production environment variables"
echo ""
read -p "Press Enter after rotating OpenAI key (or skip if not used)..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  STEP 4: Update Production Deployments${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo ""
echo "Update environment variables in all production environments:"
echo ""
echo "For Vercel:"
echo "  1. Dashboard → Project → Settings → Environment Variables"
echo "  2. Update: MONGO_URI, JWT_SECRET, OPENAI_API_KEY"
echo "  3. Redeploy: Deployments → Latest → Redeploy"
echo ""
echo "For Railway:"
echo "  1. Project → Variables"
echo "  2. Update variables"
echo "  3. Automatic redeploy triggered"
echo ""
echo "For Render:"
echo "  1. Dashboard → Web Service → Environment"
echo "  2. Update variables"
echo "  3. Manual Deploy → Deploy Latest Commit"
echo ""
read -p "Press Enter after updating production..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  STEP 5: Verify and Test${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo ""
echo "1. Test local environment:"
echo "   cd backend && npm start"
echo "   - Verify MongoDB connection"
echo "   - Test login/authentication"
echo "   - Test API endpoints"
echo ""
echo "2. Test production environment:"
echo "   - Visit production URL"
echo "   - Test login"
echo "   - Create test booking"
echo "   - Verify all features work"
echo ""
echo "3. Monitor logs for errors:"
echo "   - Check application logs"
echo "   - Watch for authentication failures"
echo "   - Monitor database connections"
echo ""
read -p "Press Enter after verification..."

echo ""
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  STEP 6: Clean Git History (Advanced)${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}⚠️  WARNING: This is destructive and affects all contributors!${NC}"
echo ""
echo "The .env file is in git history and can still be accessed."
echo "To completely remove it from history (requires force push):"
echo ""
echo "1. Install BFG Repo-Cleaner:"
echo "   brew install bfg  # macOS"
echo "   # or download from: https://rtyley.github.io/bfg-repo-cleaner/"
echo ""
echo "2. Clone a fresh copy:"
echo "   git clone --mirror git@github.com:adem1273/gnb-transfer.git"
echo ""
echo "3. Remove .env from history:"
echo "   bfg --delete-files .env gnb-transfer.git"
echo "   cd gnb-transfer.git"
echo "   git reflog expire --expire=now --all"
echo "   git gc --prune=now --aggressive"
echo ""
echo "4. Force push (⚠️  DANGEROUS):"
echo "   git push --force"
echo ""
echo "5. All contributors must re-clone:"
echo "   git clone git@github.com:adem1273/gnb-transfer.git"
echo ""
echo -e "${RED}Alternative: Create new private repository and migrate code${NC}"
echo "  This is safer if you have many contributors."
echo ""
read -p "Press Enter to continue..."

echo ""
echo -e "${GREEN}✅  Secret Rotation Checklist Complete!${NC}"
echo ""
echo "Summary of actions taken:"
echo "  ✓ MongoDB credentials rotated"
echo "  ✓ JWT_SECRET rotated"
echo "  ✓ OpenAI API key rotated (if applicable)"
echo "  ✓ Production environments updated"
echo "  ✓ Applications tested and verified"
echo ""
echo "Final steps:"
echo "  1. Document new secrets securely (password manager)"
echo "  2. Update team documentation with new connection strings"
echo "  3. Monitor logs for 24-48 hours"
echo "  4. Consider setting up secret scanning in CI"
echo ""
echo -e "${YELLOW}⚠️  REMEMBER: Git history still contains old secrets!${NC}"
echo "   Old secrets are now invalid but history should be cleaned."
echo "   Follow Step 6 above or migrate to new repository."
echo ""
echo "For future prevention:"
echo "  - Never commit .env files"
echo "  - Use .env.example for templates"
echo "  - Enable pre-commit hooks"
echo "  - Use secret scanning tools"
echo ""
echo "Questions? Contact the security team."
echo ""
